version: '3'
services:
  decentralized-iso20022-internal:
    build:
      context: .
      args:
        - STORES_FOLDER=src/main/resources
    environment:
      - spring.profiles.active=internal
    ports:
      - "8080:8080"
