version: '3'
services:
  decentralized-iso20022-external:
    build:
      context: .
      args:
        - STORES_FOLDER=src/main/resources
    environment:
      - spring.profiles.active=external
    ports:
      - "443:443"
