name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: cactu5/decentralized-ISO20022-1

    - name: Checkout to active branch
      run: |
        git fetch origin
        git checkout ${{ github.head_ref }}

    - name: Build with Maven in Docker
      run: |
        docker network create mynetwork
        docker build -t mockbanksystem mock-bank-system
        docker run -d --network=mynetwork --name=mockbanksystem mockbanksystem
        docker build --network=mynetwork -t decentralizediso20022 -f Dockerfile-ci decentralizediso20022
        docker run --env PROFILE=internal -d --network=mynetwork --name=decentralizediso20022internal -f Dockerfile-ci decentralizediso20022
        docker run --env PROFILE=external -d --network=mynetwork --name=decentralizediso20022external -f Dockerfile-ci decentralizediso20022
