name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: cactu5/decentralized-ISO20022-1

    - name: Checkout to active branch
      run: |
        git fetch origin
        git checkout ${{ github.head_ref }}

    - name: Build with Maven in Docker
      run: |
        chmod +x ./demo.sh
        ./demo.sh
        curl -X POST http://localhost/api/v1/pacs
