name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}

    - name: Checkout to active branch
      run: |
        git fetch origin
        git checkout ${{ github.head_ref }}

    - name: Build with Maven in Docker
      run: |
        docker network create mynetwork
        docker build -t mockbanksystem mock-bank-system
        docker run -d --network=mynetwork --name=mockbanksystem mockbanksystem
        docker build --network=mynetwork -t decentralizediso20022 -f decentralizediso20022/Dockerfile-ci decentralizediso20022

    - name: Generate Javadoc
      run: |
        cd decentralizediso20022
        mvn javadoc:javadoc

    - name: Upload Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: decentralizediso20022/docs/apidocs/

